/* eslint-disable quotes */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "@onruntime/next-link";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>

        <p className={styles.description}>
          This is an example of{" "}
          <Link
            href={"https://npmjs.com/package/@onruntime/next-link"}
            className={styles.code}
          >
            @onruntime/next-link
          </Link>
        </p>

        <div className={styles.grid}>
          <Link href="/hello-world" className={styles.card}>
            <h2>Internal Href &rarr;</h2>
            <p>Input</p>
            <pre className={styles.code}>
              <span>{`<Link href="/hello-world">`}</span>
              <span>{`  // ...`}</span>
              <span>{`</Link>`}</span>
            </pre>
            <p>Output</p>
            <pre className={styles.code}>
              <span>{`<a href="/hello-world">`}</span>
              <span>{`  // ...`}</span>
              <span>{`</a>`}</span>
            </pre>
          </Link>

          <Link href="https://onruntime.com" className={styles.card}>
            <h2>External Href &rarr;</h2>
            <p>Input</p>
            <pre className={styles.code}>
              <span>{`<Link href="https://onruntime.com">`}</span>
              <span>{`  // ...`}</span>
              <span>{`</Link>`}</span>
            </pre>
            <p>Output</p>
            <pre className={styles.code}>
              <span>{`<a`}</span>
              <span>{`  href="https://onruntime.com"`}</span>
              <span>{`  target="_blank"`}</span>
              <span>{`  rel="noopener noreferrer"`}</span>
              <span>{`>`}</span>
              <span>{`  // ...`}</span>
              <span>{`</a>`}</span>
            </pre>
          </Link>

          <Link className={styles.card}>
            <h2>Undefined Href &rarr;</h2>
            <p>Input</p>
            <pre className={styles.code}>
              <span>{`<Link>`}</span>
              <span>{`  // ...`}</span>
              <span>{`</Link>`}</span>
            </pre>
            <p>
              Output (with{" "}
              <code
                className={styles.code}
                style={{
                  display: "inline-block",
                }}
              >
                cursor: default
              </code>
              )
            </p>
            <pre className={styles.code}>
              <span>{`<a>`}</span>
              <span>{`  // ...`}</span>
              <span>{`</a>`}</span>
            </pre>
          </Link>

          <Link
            onClick={() => router.push("/hello-world")}
            className={styles.card}
          >
            <h2>Undefined Href with onClick &rarr;</h2>
            <p>Input</p>
            <pre className={styles.code}>
              <span>{`<Link`}</span>
              <span>{`  onClick={() => router.push("/hello-world")}`}</span>
              <span>{`>`}</span>
              <span>{`  // ...`}</span>
              <span>{`</Link>`}</span>
            </pre>
            <p>Output</p>
            <pre className={styles.code}>
              <span>{`<a>`}</span>
              <span>{`  // ...`}</span>
              <span>{`</a>`}</span>
            </pre>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
